#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#    password: Abhi2@ankur
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#
## Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#
#  jpa:
#    hibernate:
#    ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 9999